13-Capstone/Capstone.Web/Models/ErrorViewModel.cs
using System;

namespace Capstone.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

13-Capstone/Capstone.Web/Models/Park.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class Park
    {
        public string ParkCode { get; set; }
        public string ParkName { get; set; }
        public string State { get; set; }
        public int Acreage { get; set; }
        public int ElevationInFeet { get; set; }
        public double MilesOfTrail { get; set; }
        public int NumberOfCampsites { get; set; }
        public string Climate { get; set; }
        public int YearFounded { get; set; }
        public int AnnualVisitorCount { get; set; }
        public string InspirationalQuote { get; set; }
        public string InspirationalQuoteSource { get; set; }
        public string ParkDescription { get; set; }
        public int EntryFee { get; set; }
        public int NumberOfAnimalSpecies { get; set; }

 
    }
}

13-Capstone/Capstone.Web/Models/ParkInfo.cs
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class ParkInfo
    {
        public Park park { get; set; }
        public List<Weather> weather { get; set; }
    }
}

13-Capstone/Capstone.Web/Models/Survey.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class Survey
    {

        [Required]
        public string ParkCode { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string ActivityLevel { get; set; }

        public string Results { get; set; }

        public string ParkName { get; set; }
 
    }
}

13-Capstone/Capstone.Web/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class Weather
    {
        public string ParkCode { get; set; }
        public int FiveDayForecastValue { get; set; }
        public int Low { get; set; }
        public int High { get; set; }
        public string Forecast { get; set; }


        public string Unit { get; set; }



        public int ConverToCelcius(int farenheit)
        {
            int finalCelcius;

            finalCelcius = (int)((farenheit - 32) * (5 / 9.0));

            return finalCelcius;
        }


    }
}

13-Capstone/Capstone.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Capstone.Web.Models;
using Capstone.Web.DAL;

namespace Capstone.Web.Controllers
{
    public class HomeController : Controller
    {

    
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

13-Capstone/Capstone.Web/Controllers/ParksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Capstone.Web.Extensions;
using Microsoft.AspNetCore.Http;
using SessionExtensions = Capstone.Web.Extensions.SessionExtensions;

namespace Capstone.Web.Controllers
{
    public class ParksController : HomeController
    {
        IParkDao parkDao;
        IWeatherDao weatherDao;

        public ParksController(IParkDao parkDao, IWeatherDao weatherDao)
        {
            this.parkDao = parkDao;
            this.weatherDao = weatherDao;
        }

        public IActionResult Index()
        {
            List<Park> parks = parkDao.GetParks();      
            return View(parks);
        }
        
        public IActionResult Detail(string id)
        {
            ParkInfo parkinfo = new ParkInfo();

            parkinfo.park = parkDao.GetParkDetail(id);
            parkinfo.weather = weatherDao.GetWeather(id);
            string current = "";
            if (HttpContext.Session.GetString("Temperature") is null)
            {
                current = "F";
            }
            else
            {
                current = HttpContext.Session.GetString("Temperature").ToString();
            }


            if (current == "F")
            {
                // TODO: write boolean tests to distinguid between farenheit and celcius -- BOOLEAN Properties.
                foreach (var item in parkinfo.weather)
                {
                    item.High = item.High;
                    item.Low = item.Low;

                    item.Unit = current;
                }
            }

            else if (current == "C")
            {
                foreach (var item in parkinfo.weather)
                {
                    item.High = item.ConverToCelcius(item.High);
                    item.Low = item.ConverToCelcius(item.Low);
                    item.Unit = current;
                }

            }



            return View(parkinfo);
        }


        public IActionResult SetTempMeasurement(string id)
        {
            string current = "";
            if (HttpContext.Session.GetString("Temperature") is null)
            {
                current = "F";
            }
            else
            {
                current = HttpContext.Session.GetString("Temperature").ToString();
            }
     

            if (current == "F")
            {
                current = "C";
            }

            else
            {
                current = "F";
            }


            HttpContext.Session.SetString("Temperature", current);
            
            return RedirectToAction("Detail", new {id = @id } );

        }
    }
}

13-Capstone/Capstone.Web/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {
        private ISurveyDao surveyDao;
        //Inject controller
        public SurveyController(ISurveyDao surveyDao)
        {

            this.surveyDao = surveyDao;
        }


        public IActionResult Index()
        {
            IList<Survey> survey = surveyDao.GetTopSurveys();
            return View(survey);
        }

        [HttpGet]
        public IActionResult SaveNewSurvey()
        {
            ViewBag.names = surveyDao.GetParkNames();
            Survey survey = new Survey();
            return View(survey);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveNewSurvey(Survey post)
        {
            if (!ModelState.IsValid)
            {
                return View("SaveNewSurvey", post);

            }
            surveyDao.SaveNewSurvey(post);

            return RedirectToAction("Index");
        }



    }
}

13-Capstone/Capstone.Web/Views/Parks/Detail.cshtml
@model ParkInfo
@{
    ViewData["Title"] = "Detail";


}
<style>

    .fun-fact {
        background-color: lightgray;
        font-weight: 600;
    }

    .weather {
        background-color: lightgray;
    }
</style>

<br />
<img style="width:30%;" src="~/images/@(Model.park.ParkCode).jpg" /><br />
<div class="fun-fact">
    <h1 style="text-align:center;">@Model.park.ParkName </h1> <br />

    <p>@Model.park.ParkDescription </p> <br />

    Acreage: @Model.park.Acreage <br />
    Annual Visitors: @Model.park.AnnualVisitorCount <br />
    Elevation(in ft): @Model.park.ElevationInFeet <br />
    Entry Fee: $@Model.park.EntryFee <br />
    Inspirational Quote: <i>@Model.park.InspirationalQuote </i>
    <span style="text-align:right;">~@Model.park.InspirationalQuoteSource </span>  <br />
    Miles Of Trail: @Model.park.MilesOfTrail <br />
    Number Of Animal Species: @Model.park.NumberOfAnimalSpecies <br />
    Number Of Campsites: @Model.park.NumberOfCampsites <br />
    State: @Model.park.State <br />
    Year Founded: @Model.park.YearFounded <br />
</div>

<h2 style="text-align:center;">Weather Forecast</h2> <br />
<a asp-action="SetTempMeasurement" asp-route-id="@Model.park.ParkCode" class="btn btn-success">Change Between Farenheit and Celsius </a><br />
<div class="weather">
    @foreach (var item in Model.weather)
    {
        <div style="width: 220px; display:inline-block; vertical-align:top; text-align:center;">
            <img style="width: 50%" src="~/images/@(item.Forecast).png" /><br />


            @switch (item.FiveDayForecastValue)
            {
                case 1:
                    <div style="font-weight:700; color:#0094ff; font-size: 22px;">Today</div>;
                    break;
                case 2:
                    <div style="font-weight:700;">Monday</div>;
                    break;
                case 3:
                    <div style="font-weight:700;">Tuesday</div>
                    break;
                case 4:
                    <div style="font-weight:700;">Wednesday</div>
                    break;
                case 5:
                    <div style="font-weight:700;">Thursday</div>
                    break;
                default:<br />
                    break;


            }
            @item.Forecast
            @switch (item.Forecast)
            {
                case "snow":
                    <div>Pack your snow shoes!</div>;
                    break;
                case "rain":
                    <div>Pack your rain gear and wear waterproof shoes!</div>;
                    break;
                case "thunderstorms":
                    <div>Seek shelter and avoid hiking on exposed ridges!</div>
                    break;
                case "sun":
                    <div>Pack sun block!</div>
                    break;
                default:<br />
                    break;
            }



            <div>High Temp  @item.High&deg;@item.Unit</div> <br />
            <div>Low Temp  @item.Low&deg;@item.Unit</div> <br />



            @if (item.High >= 75 && item.Unit == "F" || item.High >= 24 && item.Unit == "C")
            {

                <div>Bring an extra gallon of water!</div>

            }

            @if (item.Low <= 20 && item.Unit == "F" || item.Low <= -6 && item.Unit == "C")
            {
                <div>Warning! Low temperature, be cautious of exposure.</div>

            }

            @if (item.High - item.Low >= 20 && item.Unit == "F" || item.High - item.Low >= 11 && item.Unit == "C")
            {

                <div>Wear breathable layers!</div>

            }

            <br />
        </div>
    }
</div>

13-Capstone/Capstone.Web/Views/Parks/Index.cshtml
@model IEnumerable<Capstone.Web.Models.Park>

@{
    ViewData["Title"] = "Index";
}

<h2><img style="width:33%" src="~/images/logo.png" /></h2>


<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Park Name
            </th>
            <th>
                Location
            </th>

            <th>
                Description
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a class="product-image" asp-controller="Parks" asp-action="Detail" asp-route-id=@item.ParkCode> <img src="~/images/@(item.ParkCode).jpg" /></a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParkName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.ParkDescription)
            </td>

        </tr>
}
    </tbody>
</table>

13-Capstone/Capstone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capstone.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Parks" asp-action="Index" class="navbar-brand">National Park Weather App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Parks" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Survey" asp-action="Index">Survey</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Capstone.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

13-Capstone/Capstone.Web/Views/Survey/Index.cshtml
@model IEnumerable<Capstone.Web.Models.Survey>

@{
    ViewData["Title"] = "Index";
}

<h1><img style="width:33%" src="~/images/logo.png" /></h1>
<h2 style="text-align:center; font-weight: 600; ">Survey Results</h2>

<p>
    <a asp-action="SaveNewSurvey" style="font-weight: 600;" class="btn btn-success" >Submit New Survey </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
              
            </th>
            <th>
              Park 
            </th>
            <th>
              Votes
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img style="width:30%" src="~/images/@(item.ParkCode).jpg" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParkName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Results)
            </td>

        </tr>
}
    </tbody>
</table>

13-Capstone/Capstone.Web/Views/Survey/SaveNewSurvey.cshtml
@model Capstone.Web.Models.Survey

@{
    ViewData["Title"] = "SaveNewSurvey";
    Dictionary<string, string> names = new Dictionary<string, string>();


}

<h2>SaveNewSurvey</h2>

<h4>Survey</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveNewSurvey">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="@Model.ParkCode"> Select Park </label>
            <select asp-for="@Model.ParkCode">
                @if (names != null)
                {

                    names = ViewBag.names;
                    @foreach (KeyValuePair<string, string> item in names)
                    {

                        <option value="@item.Key">@item.Value </option>

                    }

                }
            </select> 
                    
 
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select name="State">
                    <option value="AL">AL</option>
                    <option value="AK">AK</option>
                    <option value="AZ">AZ</option>
                    <option value="AR">AR</option>
                    <option value="CA">CA</option>
                    <option value="CO">CO</option>
                    <option value="CT">CT</option>
                    <option value="DE">DE</option>
                    <option value="FL">FL</option>
                    <option value="GA">GA</option>
                    <option value="HI">HI</option>
                    <option value="ID">ID</option>
                    <option value="IL">IL</option>
                    <option value="IN">IN</option>
                    <option value="IA">IA</option>
                    <option value="KS">KS</option>
                    <option value="KY">KY</option>
                    <option value="LA">LA</option>
                    <option value="ME">ME</option>
                    <option value="MD">MD</option>
                    <option value="MA">MA</option>
                    <option value="MI">MI</option>
                    <option value="MN">MN</option>
                    <option value="MS">MS</option>
                    <option value="MO">MO</option>
                    <option value="MT">MT</option>
                    <option value="NE">NE</option>
                    <option value="NV">NE</option>
                    <option value="NH">NH</option>
                    <option value="NJ">NJ</option>
                    <option value="NM">NM</option>
                    <option value="NY">NY</option>
                    <option value="NC">NC</option>
                    <option value="ND">ND</option>
                    <option value="OH">OH</option>
                    <option value="OK">OK</option>
                    <option value="OR">OR</option>
                    <option value="PA">PA</option>
                    <option value="RI">RI</option>
                    <option value="SC">SC</option>
                    <option value="SD">SD</option>
                    <option value="TN">TN</option>
                    <option value="TX">TX</option>
                    <option value="UT">UT</option>
                    <option value="VT">VT</option>
                    <option value="VA">VA</option>
                    <option value="WA">WA</option>
                    <option value="WV">WV</option>
                    <option value="WI">WI</option>
                    <option value="WY">WY</option>

                </select>
            </div>
            <div class="form-group">
                <label asp-for="ActivityLevel" class="control-label"></label> <br />
                <select name="activityLevel">
                    <option value="Inactive">Inactive</option>
                    <option value="Sedentary">Sedentary</option>
                    <option value="active">active</option>
                    <option value="extremelyactive">extremely active</option>
                </select>


            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}